import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex gap-10 items-center bg-gray-700 p-5 justify-center">
          <ul className="flex gap-7 items-center text-white">
            <Link href={"/"}>
              <li className="cursor-pointer text-2xl font-semibold">Home</li>
            </Link>
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
